site_name: Threat Matrix for Kubernetes
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
  logo: assets/Microsoft.png
  favicon: assets/mdc.png
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
nav:
  - Tactics: 
    - 'index.md'
    - Initial Access:
      - 'tactics/InitialAccess/index.md'
      - Using Cloud Credentials: 'tactics/InitialAccess/Using Cloud Credentials.md'
      - Compromised Image In Registry: 'tactics/InitialAccess/Compromised Image In Registry.md'
      - Kubeconfig file: 'tactics/InitialAccess/Kubeconfig file.md'
      - Application Vulnerability: 'tactics/InitialAccess/Application Vulnerability.md'
      - Exposed Dashboard: 'tactics/InitialAccess/Exposed Dashboard.md'
      - Exposed Sensitive Interfaces: 'tactics/InitialAccess/Exposed sensitive interfaces.md'
    - Execution:
      - 'tactics/Execution/index.md'
      - Exec Into Container: 'tactics/Execution/Exec into container.md'
      - Bash/cmd Inside Container: 'tactics/Execution/bash or cmd inside container.md'
      - New Container: 'tactics/Execution/New Container.md'
      - Application Exploit (RCE): 'tactics/Execution/Application Exploit (RCE).md'
      - SSH Server Running Inside Container: 'tactics/Execution/SSH server running inside container.md'
      - Sidecar Injection: 'tactics/Execution/Sidecar Injection.md'
    - Persistence:
      - 'tactics/Persistence/index.md'
      - Backdoor Container: 'tactics/Persistence/Backdoor container.md'
      - Writable hostPath Mount: 'tactics/Persistence/Writable hostPath mount.md'
      - Kubernetes CronJob: 'tactics/Persistence/Kubernetes CronJob.md'
      - Malicious Admission Controller: 'tactics/Persistence/Malicious admission controller.md'
    - Privilege Escalation:
      - 'tactics/PrivilegeEscalation/index.md'
      - Privileged Container: 'tactics/PrivilegeEscalation/Privileged container.md'
      - Cluster-admin Binding: 'tactics/PrivilegeEscalation/Cluster-admin binding.md'
      - Writable hostPath Mount: 'tactics/Persistence/Writable hostPath mount.md'
      - Access Cloud Resources: 'tactics/PrivilegeEscalation/Access cloud resources.md'
    - Defense Evasion:
      - 'tactics/DefenseEvasion/index.md'
      - Clear Container Logs: 'tactics/DefenseEvasion/Clear container logs.md'
      - Delete Kubernetes Events: 'tactics/DefenseEvasion/Delete K8S events.md'
      - Pod or Container Name Similarily: 'tactics/DefenseEvasion/Pod or container name similarily.md'
      - Connect from Proxy Server: 'tactics/DefenseEvasion/Connect from Proxy server.md'
    - Credential Access:
      - 'tactics/CredentialAccess/index.md'
      - List Kubernetes Secrets: 'tactics/CredentialAccess/List K8S secrets.md'
      - Mount Service Principal: 'tactics/CredentialAccess/Mount service principal.md'
      - Access Container Service Account: 'tactics/CredentialAccess/Access container service account.md'
      - Application Credentials in Configuration Files: 'tactics/CredentialAccess/Application credentials in configuration files.md'
      - Access Managed Identity Credentials: 'tactics/CredentialAccess/Access managed identity credentials.md'
      - Malicious Admission Controller: 'tactics/Persistence/Malicious admission controller.md'
    - Discovery:
      - 'tactics/Discovery/index.md'
      - Access Kubernetes API Server: 'tactics/Discovery/Access the K8S API server.md'
      - Access Kubelet API: 'tactics/Discovery/Access Kubelet API.md'
      - Network Mapping: 'tactics/Discovery/Network mapping.md'
      - Access Kubernetes Dasbhoard: 'tactics/Discovery/Access Kubernetes dasbhoard.md'
      - Instance Metadata API: 'tactics/Discovery/Instance Metadata API.md'
    - Lateral Movement:
      - 'tactics/LateralMovement/index.md'
      - Access Cloud Resources: 'tactics/PrivilegeEscalation/Access cloud resources.md'
      - Container Service Account: 'tactics/CredentialAccess/Access container service account.md'
      - Cluster Internal Networking: 'tactics/LateralMovement/Cluster internal networking.md'
      - Application Credentials in Configuration Files: 'tactics/CredentialAccess/Application credentials in configuration files.md'
      - Writable hostPath Mount: 'tactics/Persistence/Writable hostPath mount.md'
      - Exposed Dashboard: 'tactics/InitialAccess/Exposed Dashboard.md'
      - Access tiller endpoint: 'tactics/LateralMovement/Access tiller endpoint.md'
      - CoreDNS Poisoning: 'tactics/LateralMovement/CoreDNS poisoning.md'
      - ARP poisoning and IP spoofing: 'tactics/LateralMovement/ARP poisoning and IP spoofing.md'
    - Collection:
      - 'tactics/Collection/index.md'
      - Images from a Private Registry: 'tactics/Collection/images from a private registry.md'
    - Impact:
      - 'tactics/Impact/index.md'
      - Data Destruction: 'tactics/Impact/Data destruction.md'
      - Resource Hijacking: 'tactics/Impact/Resource hijacking.md'
      - Denial of Service: 'tactics/Impact/Denial of service.md'
  - Mitigations: 
    - 'mitigations/index.md'
    - Multi-factor Authentication: 'mitigations/MS-M9001 Multi-factor Authentication.md'
  - About: 'about.md'