site_name: Threat Matrix for Kubernetes
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
  logo: assets/Microsoft.png
  favicon: assets/mdc.png
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
nav:
  - Tactics: 
    - 'index.md'
    - Initial Access:
      - 'tactics/InitialAccess/index.md'
      - Using Cloud Credentials: 'tactics/InitialAccess/Using Cloud Credentials.md'
      - Compromised Image In Registry: 'tactics/InitialAccess/Compromised Image In Registry.md'
      - Kubeconfig file: 'tactics/InitialAccess/Kubeconfig file.md'
      - Application Vulnerability: 'tactics/InitialAccess/Application Vulnerability.md'
      - Exposed Dashboard: 'tactics/InitialAccess/Exposed Dashboard.md'
      - Exposed Sensitive Interfaces: 'tactics/InitialAccess/Exposed sensitive interfaces.md'
    - Execution:
      - 'tactics/Execution/index.md'
      - Exec Into Container: 'tactics/Execution/Exec into container.md'
      - Bash/cmd Inside Container: 'tactics/Execution/bash or cmd inside container.md'
      - New Container: 'tactics/Execution/New Container.md'
      - Application Exploit (RCE): 'tactics/Execution/Application Exploit (RCE).md'
      - SSH Server Running Inside Container: 'tactics/Execution/SSH server running inside container.md'
      - Sidecar Injection: 'tactics/Execution/Sidecar Injection.md'
    - Persistence:
      - 'tactics/Persistence/index.md'
    - Privilege Escalation:
      - 'tactics/PrivilegeEscalation/index.md'
    - Defense Evasion:
      - 'tactics/DefenseEvasion/index.md'
    - Credential Access:
      - 'tactics/CredentialAccess/index.md'
    - Discovery:
      - 'tactics/Discovery/index.md'
    - Lateral Movement:
      - 'tactics/LateralMovement/index.md'
    - Collection:
      - 'tactics/Collection/index.md'
    - Impact:
      - 'tactics/Impact/index.md'
  - Mitigations: 
    - 'mitigations/index.md'
  - About: 'about.md'